name: Build ImagesToPdf

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore ImagesToPdf.sln

      - name: Build Solution
        run: |
          msbuild ImagesToPdf.sln ^
            /p:Configuration=Release ^
            /p:Platform="Any CPU"

      - name: Display Build Output
        run: |
          dir ImagesToPdf\bin\Release